[package]
name = "modernpro-cv"
version = "0.0.1"
entrypoint = "modernpro-cv.typ"
authors = [ "jxpeng98"]
repository = "https://github.com/jxpeng98/Typst-CV-Resume"
license = "MIT"
description = "A CV template inspired by Deedy-Resume."
keywords = ["cv", "resume"]
categories = ["cv"]

[template]
path = "template"
entrypoint = ["main_single.typ", "main_double.typ"]
thumbnail = "thumbnail.png"
